task: detection

evaluator:
  type: CocoEvaluator
  iou_types: ['bbox', ]

num_classes: 777 # your dataset classes
remap_mscoco_category: False

train_dataloader:
  type: DataLoader
  dataset:
    type: CocoDetection
    img_folder: /workspace/datasets/spac_coco_formatted/train
    ann_file: /workspace/datasets/spac_coco_formatted/annotations/instances_train.json
    return_masks: False
    # transforms:
    #   type: Compose
    #   ops: ~
  shuffle: True
  num_workers: 4
  drop_last: True
  collate_fn:
    type: BatchImageCollateFunction


val_dataloader:
  type: DataLoader
  dataset:
    type: CocoDetection
    img_folder: /workspace/datasets/spac_coco_formatted/valid
    ann_file: /workspace/datasets/spac_coco_formatted/annotations/instances_valid.json
    return_masks: False
    # transforms:
    #   type: Compose
    #   ops: ~
  shuffle: False
  num_workers: 4
  drop_last: False
  collate_fn:
    type: BatchImageCollateFunction
